### ISSUE TITLE
Possible BUG in TwoQubit-VQE.ipynb

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/SSSS#6] opened 2019-05-03 16:26 UTC
In the last `ChainBlock` in `Out[370]`, the 2 MeasureBlocks are printed as:
```
   ├─ Measure{2,1,AbstractBlock}
   └─ Measure{2,1,AbstractBlock}
```
Should one be `Measure{2,2,AbstractBlock}` for it should be put on the 2nd line of the circuit? Maybe you should fix the function `twoqubit_circuit` in `Out[369]`.

**Comment by GiggleLiu** [comment] 2019-05-03 17:24
This is not a bug, the second type parameter means "how many qubits" got measured. So, it is the printing should be improved. :sorry

**Comment by quantumbfs0** [comment] 2019-05-08 23:34
@GiggleLiu Shall we close this if you already improved print?

**Closed as completed** 2019-05-09 09:59 UTC
